### ISSUE TITLE
Make can't find Surelog header file

### ISSUE THREAD

**Issue by kiteloopdesign** [pieter3d/simview#15]
Just leaving here some instructions on to how to build in Fedora 35. Below are some packages I needed to install in order to build both Surelog and simview. Note that others might already been installed on my system, so this is not a complete list

```
sudo dnf install zlib-devel
sudo dnf install libuuid-devel
sudo dnf install lcov
sudo dnf install swig
sudo dnf install uuid-devel
sudo dnf install cmake
```
However, when installing simview, `cmake ..` works properly, but it is failing when building. I am getting following error, looks like it can't figure out where surelog has been installed. Any way to pass surelog path to `make` ?

```
[ 74%] Building CXX object src/CMakeFiles/simview.dir/color.cc.o
[ 76%] Building CXX object src/CMakeFiles/simview.dir/design_tree_item.cc.o
In file included from /home/kitesutra/cad/simview/src/design_tree_item.cc:5:
/home/kitesutra/cad/simview/src/workspace.h:4:10: fatal error: surelog/surelog.h: No such file or directory
    4 | #include <surelog/surelog.h>
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/CMakeFiles/simview.dir/build.make:90: src/CMakeFiles/simview.dir/design_tree_item.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:3216: src/CMakeFiles/simview.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

Thanks

**Comment by kiteloopdesign** [comment]
Ok, so Surelog github mentions that there is a path that needs to be set in projects making use of Surelog. So I set this variable inside `simview/CMakeLists.txt`

```
set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} /home/kitesutra/cad/Surelog)
find_package(Surelog)
```
And I add `target_link_libraries(<your project name> Surelog)`

But then I get this error

```
CMake Error at CMakeLists.txt:59 (target_link_libraries):
Cannot specify link libraries for target "SimView" which is not built by
this project.
```

I think that `cmake` is taking the location properly, as it throws a warning if it does not find the package, so I think this is OK. I think I might be missing something on adding that `target_link_libraries`, I do not think is supposed to go there?

Also, note the "S" of Surelog versus the "s" of surelog. Currently using uppercase "S" as the project is named like so. But the `include` of the error is expecting a "surelog"?

Apologies if I am missing something obvious here but I am not familiar with cmake/g++ stuff

**Comment by pieter3d** [comment]
where did surelog get installed? On my Ubuntu installation it ends up in `/usr/local/include/surelog/`, which cmake discovers with the `find_package(Surelog REQUIRED)` statement in `src/CMakeLists.txt`

**Comment by kiteloopdesign** [comment]
Thanks Pieter

It gets installed in `/usr/local/include/**S**urelog`.

I will try that folder instead inside `set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH}` and run make again. I guess I used the donwload/build folder as opposed as the installation one

**Comment by kiteloopdesign** [comment]
The "S" was supposed to come up as **S**

**Comment by pieter3d** [comment]
When you build surelog, follow it up with `sudo make install`

**Comment by kiteloopdesign** [comment]
Same error. I am confused now by your mention to "statement in src/CMakeLists.txt"... I see no such file inside *simview/build/src* folder. The CMakeLists.txt I am editing is the one in *simview/* folder

To clarify what I am doing. I am inside *simview/build* folder. From here I do the following

```
cmake ..                                                                                                                                                                                                                                              
-- The C compiler identification is GNU 11.2.1
-- The CXX compiler identification is GNU 11.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Submodule update
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Found Python: /usr/bin/python3.10 (found version "3.10.2") found components: Interpreter 
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.11") 
-- Found Curses: /usr/lib64/libcurses.so  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/kitesutra/cad/simview/build
```
Then I do `make` and eventually get that error

**Comment by pieter3d** [comment]
There's another cmake file in the src dir (not in build)

**Comment by kiteloopdesign** [comment]
Ok, I see now that cmake file.

So, as per the instructions on Surelog:

![image](https://user-images.githubusercontent.com/17339330/158037445-6c68d365-b010-45cc-be03-a7a388d4ac3c.png)

I update that src/CMakeLists.txt with the following:

![image](https://user-images.githubusercontent.com/17339330/158037502-51c365dc-b32f-492a-820e-1326a5e781de.png)

Then I go to simview/build and do `make`, and get this error

```
CMake Error at src/CMakeLists.txt:42 (target_link_libraries):
  The plain signature for target_link_libraries has already been used with
  the target "simview".  All uses of target_link_libraries with a target must
  be either all-keyword or all-plain.

  The uses of the plain signature are here:

   * src/CMakeLists.txt:40 (target_link_libraries)
```

Apologies if I can't offer much more details but I am at lost with this

**Comment by pieter3d** [comment]
You can see in that file I already included surelog, so you'll get an error for doing it a second time.

Did you get surelog installed after you built it (outside simview)?

**Comment by kiteloopdesign** [comment]
> You can see in that file I already included surelog, so you'll get an error for doing it a second time.

Yep, I was just trying nevertheless as I w/o it I am getting that error at 76% ...

> Did you get surelog installed after you built it (outside simview)?

Yes, it is installed via `sudo make install`, and, as a matter of fact, working properly (at least the executable)

Thanks for the help

**Comment by pieter3d** [comment]
Okay, where did surelog get installed?

If cmake can't find it with a find_package statement, that might be a surelog issue (it should export and install a .cmake file too).

**Comment by kiteloopdesign** [comment]
It gets installed to `/usr/local/include/Surelog`. Note though that the libs get installed to `/usr/local/lib64` instead of `/usr/local/lib` (if thats of any help).

You are right in that this might be a Surelog issue. I actually can't create an executable by linking to its library. I opened an issue on [here](https://github.com/chipsalliance/Surelog/issues/2742)

Thanks

**Comment by pieter3d** [comment]
What if you just rename the install location to `surelog`, with a lower case s?

**Comment by kiteloopdesign** [comment]
That's funny. I had already tried that (softlinking `surelog->Surelog`) and it made no difference, but now it has made. I guess it was that in combination with the symlink I also used to link `/usr/lib/surelog->/usr/lib64/surelog`.

Anyway, now I get some different errors which make even less sense given that they refer to a pretty standard C++ function like cout ... 

```
[ 79%] Building CXX object src/CMakeFiles/simview.dir/main.cc.o
/home/kitesutra/cad/simview/src/main.cc: In function ‘int main(int, char**)’:
/home/kitesutra/cad/simview/src/main.cc:7:10: error: ‘cout’ is not a member of ‘std’
    7 |     std::cout
      |          ^~~~
/home/kitesutra/cad/simview/src/main.cc:4:1: note: ‘std::cout’ is defined in header ‘<iostream>’; did you forget to ‘#include <iostream>’?
    3 | #include <cstring>
  +++ |+#include <iostream>
    4 | 
/home/kitesutra/cad/simview/src/main.cc:19:14: error: ‘cout’ is not a member of ‘std’
   19 |         std::cout << "Missing wave file argument." << std::endl;
      |              ^~~~
/home/kitesutra/cad/simview/src/main.cc:19:14: note: ‘std::cout’ is defined in header ‘<iostream>’; did you forget to ‘#include <iostream>’?
/home/kitesutra/cad/simview/src/main.cc:34:10: error: ‘cout’ is not a member of ‘std’
   34 |     std::cout << "Parsing design files..." << std::endl;
      |          ^~~~
/home/kitesutra/cad/simview/src/main.cc:34:10: note: ‘std::cout’ is defined in header ‘<iostream>’; did you forget to ‘#include <iostream>’?
/home/kitesutra/cad/simview/src/main.cc:44:10: error: ‘cout’ is not a member of ‘std’
   44 |     std::cout << "Reading wave file..." << std::endl;
      |          ^~~~
/home/kitesutra/cad/simview/src/main.cc:44:10: note: ‘std::cout’ is defined in header ‘<iostream>’; did you forget to ‘#include <iostream>’?
/home/kitesutra/cad/simview/src/main.cc:46:12: error: ‘cout’ is not a member of ‘std’
   46 |       std::cout << "Problem reading wave file." << std::endl;
      |            ^~~~
/home/kitesutra/cad/simview/src/main.cc:46:12: note: ‘std::cout’ is defined in header ‘<iostream>’; did you forget to ‘#include <iostream>’?
make[2]: *** [src/CMakeFiles/simview.dir/build.make:132: src/CMakeFiles/simview.dir/main.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:3216: src/CMakeFiles/simview.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

**Comment by pieter3d** [comment]
Oof, I don't know what's going on in your system there (basic stdlib headers missing perhaps)?
Do other projects build? Or just a bare bones hello_world.c?

**Comment by kiteloopdesign** [comment]
Put together the dummy .cpp file below, and basic makefile, and it builds/works fine in my system. Maybe something in the simview's Makefile settings, messing up the build flow? That would be my guess at this stage. Unfortunately I do not know enough about cmake/c++ builds to debug this

```
#include <iostream>

using namespace std;

int main(const int argc, const char** argv) {
  cout << "Hello world!" << endl;

  return 0;
}
```

**Comment by pieter3d** [comment]
Hmm, there's  nothing weird or special about simview's cmake setup. Anyway it sounds like you're having issues with any cmake project that's trying to use Surelog in your system...

**Comment by kiteloopdesign** [comment]
This is fixed, so closing the issue. I am not sure at this stage what the solution was, as I had several things going on is parallel. I am sorry I can't give this other closing than, if you run into similar issues, have a look at Surelog closed issues; there I describe how I fixed the issues I was having, which probably also helped the ones here
