### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by timkpaine** [pieter3d/simview#17]
Hello! I have .deb and homebrew building off my PR https://github.com/pieter3d/simview/pull/16

One blocker is that this project does not currently have a version scheme that we can use on these platforms. Would you consider tagging a version (I'm happy to incorporate this information into the library itself to be displayed with -V or whatever).

**Comment by pieter3d** [comment]
Sure! Does a `v0.1` tag work for the repo in its current state?

**Comment by timkpaine** [comment]
> Sure! Does a `v0.1` tag work for the repo in its current state?

I'd say any tag is good for now just to get started, but for homebrew I will most likely need that PR.

**Comment by pieter3d** [comment]
PR merged.

**Comment by pieter3d** [comment]
https://github.com/pieter3d/simview/releases/tag/v0.1
